### ISSUE TITLE
Why is it important to add @liberation-data/agensgraph is I am using neo4j

### ISSUE THREAD

**Issue by Quadriphobs1** [liberation-data/drivine#56] opened 2020-08-18 13:03 UTC

**Comment by xv-jasper-b** [comment] 2020-08-18 22:17
Duplicate of #30 

Please follow this issue @Quadriphobs1. Contributions welcome.

**Comment by jasperblues** [comment] 2020-08-18 22:18
Duplicate of #30

Please follow this issue @Quadriphobs1. Contributions welcome.

**Closed by jasperblues** 2020-08-18 22:18 UTC

**Comment by Quadriphobs1** [comment] 2020-08-18 22:29
I have actually switched over to using bride since it's an important part of my day... But maybe I'll take a look into it at a leisure time the API for this is actually better than neode for me

**Comment by jasperblues** [comment] 2020-08-18 22:34
You are very welcome to do that. Thank you @Quadriphobs1
