### ISSUE TITLE
drivine.org a sign of status?

### ISSUE THREAD

**Issue by ark-davegoodchild** [liberation-data/drivine#112] opened 2023-03-06 14:47 UTC
Hi,

I've noticed that recently drivine.org is returning a github 404, is this a sign that this library is no longer maintained?
I thought I'd check before deciding on using it.

Thanks

**Comment by ark-davegoodchild** [comment] 2023-03-06 15:27
In fact, most links, such as to the guide, don't resolve now, where might we see the documentation?

**Comment by ark-davegoodchild** [comment] 2023-03-06 15:42
For anyone else facing the same issues, I suggest simply checking out the repository into a local directory and running a simple http service, e.g.:
```
$ mkdir help
$ cd help
$ git clone https://github.com/liberation-data/drivine.git
$ cd drivine/docs
$ npm install -g http-server
$ http-server
```

**Comment by ark-davegoodchild** [comment] 2023-03-06 15:56
The content is also available at: https://liberation-data.github.io/drivine/
Just having myself a very public discovery session, hopefully useful to someone who stumbles across it.

**Comment by jasperblues** [comment] 2023-03-06 22:50
Let me know which links didn't work, so I can fix them.

**Comment by jasperblues** [comment] 2023-03-06 22:52
Duplicate of #110

**Closed by jasperblues** 2023-03-06 22:52 UTC
